### ISSUE TITLE
路由记录问题

### ISSUE THREAD

**Issue by wotermelon** [chjtx/JTaro#1]
> 如有A、B、C、D四个页面，按顺序访问A->B->C->D，在D页面返回到B，将剩下A->B两个页面

但是这样子剩下A和B之后，按下返回键之后，依然会从B->D->C->B->A，那这样子有什么意义？

**Comment by chjtx** [comment]
@zhangmingze 是的，如果使用this.go('B')这样跳去B页会残留CD的历史记录，因此返回要使用this.go(-2)消除历史记录

**Comment by chjtx** [comment]
@zhangmingze 该问题已在v0.3.1版本修复，目前已提交到develop分支，感谢反馈！
